FORMAT: 1A

# First API
This is my first API design.

# Resource [/resoruce]
It consists of one resource called _Resource_.

## List [GET]
+ response 200 (application/json)

        { "color": "red" }

