FORMAT: 1A

# First API
This is my first API design. Hello From GitHub.

# Resource [/resource]
It consists of one resource called _Resource_.

## List [GET]
+ Response 200 (application/json)
    
        { "color": "red" }

